id: P000707
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W9088
  title: སྡོམ་གསུམ་རྣམ་ངེས་ཀྱི་འགྲེལ་པ་དཔག་བསམ་སྙེ་མ
  author: ''
  volumes:
    7473d472db8c4c5e97604237e4fe5aa1:
      image_group_id: I1KG622
      title: ''
      volume_number: 1
      total_pages: 1186
      base_file: v001.txt
