id: IF4D4AA79
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:06:43+00:00'
last_modified: '2022-06-07T12:42:50.676196+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W9088
  title: སྡོམ་གསུམ་རྣམ་ངེས་ཀྱི་འགྲེལ་པ་དཔག་བསམ་སྙེ་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5ADC:
      image_group_id: I1KG622
      title: ''
      total_pages: 1186
      order: 1
      base_file: 5ADC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
