id: IF4D4AA79
legacy_id: P000707
ocr_import_info:
  bdrc_scan_id: W9088
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T03:59:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:05:51.093152+00:00'
last_modified: 2022-09-04 13:06:15.807845
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W9088
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW9088
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྡོམ་གསུམ་རྣམ་ངེས་ཀྱི་འགྲེལ་པ་དཔག་བསམ་སྙེ་མ།
  author: སྨིན་གླིང་ལོ་ཆེན་དྷརྨ་ཤྲཱི།
statistics:
  ocr_word_mean_confidence_index: 0.5333762609028294
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I1KG622:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG622
      total_pages: 1186
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG622.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5333762609028294
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
